name: stopwatch_lafay
description: A simple sport stopwatch app for the Lafay method
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^3.0.1
  url_launcher: ^6.1.11
  duration_picker: ^1.1.1
  vibration: ^1.8.1
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
